# Generated by Django 3.0.11 on 2021-01-05 18:21

from django.db import migrations
import oscar.models.fields.decimal


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200801_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenteventquantity',
            name='quantity',
            field=oscar.models.fields.decimal.QuantityField(decimal_places=9, default=0, max_digits=36, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='shippingeventquantity',
            name='quantity',
            field=oscar.models.fields.decimal.QuantityField(decimal_places=9, default=0, max_digits=36, verbose_name='Quantity'),
        ),
    ]
